# Default values for k8s-assignment
# This is a YAML-formatted file.

global:
  namespace: k8s-assignment

# MySQL Configuration
mysql:
  enabled: true
  
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent
  
  rootPassword: "rootpassword"
  password: "userpassword"
  database: "testdb"
  username: "testuser"
  
  storage:
    size: "10Gi"
  
  service:
    port: 3306
    type: ClusterIP
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

# Nginx Configuration
nginx:
  enabled: true
  
  image:
    repository: nginx
    tag: "1.25-alpine"
    pullPolicy: IfNotPresent
  
  replicas: 3
  
  service:
    port: 80
    type: NodePort
    nodePort: 30080
  
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

# Pod Watcher Configuration (Golang only)
podWatcher:
  enabled: true
  
  # Golang-based monitoring
  image:
    repository: <your repo url>
    tag: "latest"
    pullPolicy: Always
  
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

# Network Policies Configuration
networkPolicies:
  enabled: true
  
  mysql:
    enabled: true
  
  nginx:
    enabled: true
