apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: k8s-assignment
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        
        server {
            listen 80;
            server_name localhost;
            
            location / {
                root /usr/share/nginx/html;
                index index.html;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: k8s-assignment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: init-serving-host
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          POD_NAME=$(cat /etc/podinfo/podname)
          SERVING_HOST="Host-${POD_NAME: -5}"
          POD_IP=$(hostname -i)
          
          cat > /shared/index.html << HTML
          <!DOCTYPE html>
          <html>
          <head>
              <title>Kubernetes Assignment</title>
          </head>
          <body>
              <h1>Kubernetes Assignment - Web Server</h1>
              <p><strong>Pod IP:</strong> $POD_IP</p>
              <p><strong>Serving Host:</strong> $SERVING_HOST</p>
          </body>
          </html>
          HTML
        volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
        - name: shared-data
          mountPath: /shared
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: shared-data
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: shared-data
        emptyDir: {}
      - name: podinfo
        downwardAPI:
          items:
          - path: "podname"
            fieldRef:
              fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: k8s-assignment
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort