apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-watcher
  namespace: k8s-assignment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-watcher
  template:
    metadata:
      labels:
        app: pod-watcher
    spec:
      serviceAccountName: pod-watcher
      containers:
      - name: pod-watcher
        image: alpine/k8s:1.28.2
        command: ['sh', '-c']
        args:
        - |
          echo "$(date): Starting Kubernetes Pod Watcher..."
          echo "$(date): Monitoring pods in k8s-assignment namespace"
          while true; do
            kubectl get pods -n k8s-assignment --watch --no-headers | while read line; do
              echo "$(date): Pod change detected: $line"
            done
            echo "$(date): Watcher disconnected, reconnecting..."
            sleep 2
          done
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-watcher
  namespace: k8s-assignment
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-watcher
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-watcher
subjects:
- kind: ServiceAccount
  name: pod-watcher
  namespace: k8s-assignment