{{- if .Values.networkPolicies.enabled }}
{{- if .Values.networkPolicies.mysql.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mysql-network-policy-helm
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      app: mysql-helm
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: nginx-helm
    ports:
    - protocol: TCP
      port: 3306
  egress:
  - ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
---
{{- end }}
{{- if .Values.networkPolicies.nginx.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nginx-network-policy-helm
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      app: nginx-helm
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from: []
    ports:
    - protocol: TCP
      port: 80
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: mysql-helm
    ports:
    - protocol: TCP
      port: 3306
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
---
{{- end }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all-helm
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
{{- end }}
